Repository mindfiredigital/PivotHead, pull requests merged in 2024-12, with the labels that each got.

#14 Feature/13 vercel live preview
  examples/vanilla-js-demo/.gitignore
  examples/vanilla-js-demo/package.json
  examples/vanilla-js-demo/vercel.json
  pre-commit-validation.sh
Labels: feature

#21 Feature/16 row expansion
  examples/vanilla-js-demo/lib/pivothead-core.js
  examples/vanilla-js-demo/main.js
  node_modules/.modules.yaml
  node_modules/.pnpm/lock.yaml
  packages/core/src/__test__/pivotEngine.test.ts
  packages/core/src/engine/pivotEngine.ts
  packages/core/src/index.d.ts
  packages/core/src/types/interfaces.ts
Labels: feature

#23 Feature/22 grouping of data
  examples/vanilla-js-demo/README.md
  examples/vanilla-js-demo/lib/pivothead-core.js
  examples/vanilla-js-demo/main.js
  examples/vanilla-js-demo/package.json
  package.json
  packages/core/package.json
  packages/core/src/__test__/grouping.test.ts
  packages/core/src/__test__/pivotEngine.test.ts
  packages/core/src/engine/dataProcessor.ts
  packages/core/src/engine/pivotEngine.ts
  packages/core/src/index.d.ts
  packages/core/src/index.ts
  packages/core/src/types/interfaces.ts
Labels: feature

#35 bug:[33] Add format and lint script
  .eslintrc.js
  .github/pull_request_template.md
  BRANCHING.md
  CODE_OF_CONDUCT.md
  COMMIT_MESSAGE.md
  CONTRIBUTING.md
  README.md
  examples/vanilla-js-demo/README.md
  package.json
  packages/core/README.md
  packages/core/package.json
  packages/core/src/__test__/draggable.test.ts
  packages/core/src/__test__/grouping.test.ts
  packages/core/src/__test__/pivotEngine.test.ts
  packages/core/src/__test__/sorter.test.ts
  packages/core/src/engine/aggregator.ts
  packages/core/src/engine/dataProcessor.ts
  packages/core/src/engine/filter.ts
  packages/core/src/engine/pivotEngine.ts
  packages/core/src/engine/sorter.ts
  packages/core/src/index.d.ts
  packages/core/src/index.ts
  packages/core/src/types/interfaces.ts
  packages/core/vite.config.ts
  packages/core/vitest.config.ts
  pnpm-lock.yaml
Labels: bug

#37 Enhancement/36 add standard error handlers
  .husky/pre-commit
  BRANCHING.md
  CONTRIBUTING.md
  docs/error-handling.md
  package.json
  packages/core/src/__test__/errors/BaseError.test.ts
  packages/core/src/__test__/errors/InternalError.test.ts
  packages/core/src/__test__/errors/ValidationError.test.ts
  packages/core/src/config/constants.ts
  packages/core/src/errors/ErrorHandler.ts
  packages/core/src/types/interfaces.ts
  pnpm-lock.yaml
  pre-commit-validation.sh
Labels: enhancement

#44 feat:[43] Update command for pre-commit
  .husky/pre-commit
  packages/core/src/__test__/aggregator.test.ts
  packages/core/src/__test__/errors/BaseError.test.ts
  packages/core/src/__test__/errors/InternalError.test.ts
  packages/core/src/__test__/errors/ValidationError.test.ts
  packages/core/src/engine/aggregator.ts
  packages/core/src/errors/ErrorHandler.ts
  packages/core/src/types/interfaces.ts
Labels: enhancement

#38 Feature/22 grouping data
  .github/pull_request_template.md
  .husky/pre-commit
  examples/vanilla-js-demo/lib/pivothead-core.js
  examples/vanilla-js-demo/main.js
  examples/vanilla-js-demo/testData.js
  examples/vanilla-js-demo/utils/testData.js
  packages/core/README.md
  packages/core/src/__test__/aggregator.test.ts
  packages/core/src/__test__/grouping.test.ts
  packages/core/src/engine/aggregator.ts
  packages/core/src/engine/dataProcessor.ts
  packages/core/src/engine/pivotEngine.ts
  packages/core/src/index.ts
  packages/core/src/types/interfaces.ts
  turbo.json
Labels: feature
