Repository mindfiredigital/PivotHead, pull requests merged in 2025-02, with the labels that each got.

#112 feat:111 Implement changeset
  .changeset/README.md
  .changeset/config.json
  .github/workflows/publish.yml
  package.json
  pnpm-lock.yaml
Labels: feature, enhancement

#113 Merge development to main branch for changeset implementation
  .changeset/README.md
  .changeset/config.json
  .github/pull_request_template.md
  .github/workflows/publish.yml
  BRANCHING.md
  COMMIT_MESSAGE.md
  README.md
  examples/vanilla-js-demo/conditionFormattingPopUp.js
  examples/vanilla-js-demo/lib/pivothead-core.js
  examples/vanilla-js-demo/main.js
  package.json
  packages/core/src/__test__/draggable.test.ts
  packages/core/src/__test__/pivotEngine.test.ts
  packages/core/src/__test__/sorter.test.ts
  packages/core/src/engine/aggregator.ts
  packages/core/src/engine/dataProcessor.ts
  packages/core/src/engine/pivotEngine.ts
  packages/core/src/engine/sorter.ts
  packages/core/src/types/interfaces.ts
  pnpm-lock.yaml
  pre-commit-validation.sh
Labels: feature, enhancement

#116 fix: Update publish.yml
  .github/workflows/publish.yml
  .releaserc.json
Labels: bug

#118 Add changes in .changeset/config.json
  .changeset/config.json
  .github/changeset-autogenerate.mjs
  .github/workflows/publish.yml
  examples/vanilla-js-demo/lib/pivothead-core.js
Labels: bug

#124 Exclude examples workspace from publishing
  .npmignore
  examples/vanilla-js-demo/package.json
  package.json
  packages/angular/ng-headless-pivot/.editorconfig
  packages/angular/ng-headless-pivot/.gitignore
  packages/angular/ng-headless-pivot/.vscode/extensions.json
  packages/angular/ng-headless-pivot/.vscode/launch.json
  packages/angular/ng-headless-pivot/.vscode/tasks.json
  packages/angular/ng-headless-pivot/README.md
  packages/angular/ng-headless-pivot/angular.json
  packages/angular/ng-headless-pivot/package-lock.json
  packages/angular/ng-headless-pivot/package.json
  packages/angular/ng-headless-pivot/public/favicon.ico
  packages/angular/ng-headless-pivot/src/app/app.component.html
  packages/angular/ng-headless-pivot/src/app/app.component.scss
  packages/angular/ng-headless-pivot/src/app/app.component.spec.ts
  packages/angular/ng-headless-pivot/src/app/app.component.ts
  packages/angular/ng-headless-pivot/src/app/app.config.server.ts
  packages/angular/ng-headless-pivot/src/app/app.config.ts
  packages/angular/ng-headless-pivot/src/app/app.routes.server.ts
  packages/angular/ng-headless-pivot/src/app/app.routes.ts
  packages/angular/ng-headless-pivot/src/index.html
  packages/angular/ng-headless-pivot/src/main.server.ts
  packages/angular/ng-headless-pivot/src/main.ts
  packages/angular/ng-headless-pivot/src/server.ts
  packages/angular/ng-headless-pivot/src/styles.scss
  packages/angular/ng-headless-pivot/tsconfig.app.json
  packages/angular/ng-headless-pivot/tsconfig.json
  packages/angular/ng-headless-pivot/tsconfig.spec.json
  packages/core/README.md
Labels: bug

#114 Feature/110 data sources
  README.md
  examples/vanilla-js-demo/dataSourceOptions.js
  examples/vanilla-js-demo/header.js
  examples/vanilla-js-demo/main.js
  packages/core/src/engine/pivotEngine.ts
  packages/core/src/types/interfaces.ts
Labels: feature

#126 Feature/125 changeset commit restructuring
  .changeset/changeset-autogenerate.mjs
  .github/changeset-autogenerate.mjs
  .github/workflows/publish.yml
  README.md
  examples/vanilla-js-demo/README.md
  examples/vanilla-js-demo/conditionFormattingPopUp.js
  examples/vanilla-js-demo/dataSourceOptions.js
  examples/vanilla-js-demo/fieldsPopup.js
  examples/vanilla-js-demo/formatCell.js
  examples/vanilla-js-demo/header.js
  examples/vanilla-js-demo/index.html
  examples/vanilla-js-demo/lib/pivothead-core.js
  examples/vanilla-js-demo/main.js
  pnpm-lock.yaml
  pre-commit-validation.sh
Labels: bug, enhancement

#127 changeset commit restructuring
  .changeset/changeset-autogenerate.mjs
  .github/changeset-autogenerate.mjs
  .github/workflows/publish.yml
  README.md
  examples/vanilla-js-demo/README.md
  examples/vanilla-js-demo/conditionFormattingPopUp.js
  examples/vanilla-js-demo/dataSourceOptions.js
  examples/vanilla-js-demo/fieldsPopup.js
  examples/vanilla-js-demo/formatCell.js
  examples/vanilla-js-demo/header.js
  examples/vanilla-js-demo/index.html
  examples/vanilla-js-demo/lib/pivothead-core.js
  examples/vanilla-js-demo/main.js
  packages/core/src/engine/pivotEngine.ts
  packages/core/src/types/interfaces.ts
  pnpm-lock.yaml
  pre-commit-validation.sh
Labels: bug, enhancement

#128 fix(core): fix changeset commit pattern
  .husky/publish.yml
  pre-commit-validation.sh
Labels: bug, enhancement

#129 Feature/125 changeset commit restructure
  .husky/publish.yml
  pre-commit-validation.sh
Labels: bug, enhancement
