Repository mindfiredigital/PivotHead, pull requests merged in 2025-01, with the labels that each got.

#51 Add Fields Popup with Drag-and-Drop Functionality
  examples/vanilla-js-demo/fieldsPopup.js
  examples/vanilla-js-demo/header.js
Labels: feature

#54 Feedback suggestion add comment
  examples/vanilla-js-demo/index.html
  examples/vanilla-js-demo/lib/pivothead-core.js
  package.json
  packages/core/README.md
  packages/core/src/engine/pivotEngine.ts
  pre-commit-validation.sh
Labels: feature

#58 feat:[57] Field settings popup bug fixes and features
  examples/vanilla-js-demo/fieldsPopup.js
Labels: bug, feature, enhancement

#60 bug:[59] Improved UI and formating of data
  examples/vanilla-js-demo/main.js
Labels: bug

#64 feat:[63] Dynamic conditional rendering
  examples/vanilla-js-demo/README.md
  examples/vanilla-js-demo/conditionFormattingPopUp.js
  examples/vanilla-js-demo/lib/pivothead-core.js
  examples/vanilla-js-demo/main.js
  packages/core/README.md
  packages/core/src/engine/pivotEngine.ts
Labels: feature

#72 Add CI/CD workflow for publishing on npm
  .github/workflows/publish.yml
  README.md
  package.json
Labels: feature

#74 Add Git Actions Workflow
  .github/workflows/ci.yml
Labels: feature

#83 fix: Fix issue related to publishing to npm
  examples/vanilla-js-demo/package.json
  package.json
Labels: bug, feature

#84 fix: Add changes in semantic-release workflow
  .github/workflows/publish.yml
  package.json
  pnpm-lock.yaml
Labels: bug, feature

#86 fix: Add changes in publish.yml
  .github/workflows/publish.yml
  .releaserc.json
Labels: bug, feature

#88 Update the publish.yml for automation
  .github/workflows/publish.yml
Labels: bug, feature

#90 bug:[65] Add conditional formatting for between
  examples/vanilla-js-demo/conditionFormattingPopUp.js
Labels: feature, milestore-core-1

#91 docs:[73] Update branching naming convention
  BRANCHING.md
  COMMIT_MESSAGE.md
  pre-commit-validation.sh
Labels: documentation, milestore-core-1

#99 docs:[98] Update readme header
  README.md
Labels: bug, documentation, milestore-core-1

#102 Feature/101 Code clean and improvement
  .github/pull_request_template.md
  examples/vanilla-js-demo/lib/pivothead-core.js
  examples/vanilla-js-demo/main.js
Labels: enhancement, milestore-core-1

#52 feat:[48] Sort feature implementation changes
  examples/vanilla-js-demo/main.js
  packages/core/src/__test__/pivotEngine.test.ts
  packages/core/src/__test__/sorter.test.ts
  packages/core/src/engine/aggregator.ts
  packages/core/src/engine/dataProcessor.ts
  packages/core/src/engine/pivotEngine.ts
  packages/core/src/engine/sorter.ts
  packages/core/src/types/interfaces.ts
Labels: feature, milestore-core-1

#109 feat:[104] Hide show toolbar added
  README.md
  examples/vanilla-js-demo/lib/pivothead-core.js
  examples/vanilla-js-demo/main.js
Labels: feature

#106 feat:[105] Update engine for drag drop
  README.md
  examples/vanilla-js-demo/main.js
  packages/core/src/__test__/draggable.test.ts
  packages/core/src/engine/pivotEngine.ts
  packages/core/src/types/interfaces.ts
Labels: feature
